import { useState } from 'react'
import TeacherShell, { Icon } from '../../../components/TeacherShell.jsx'

const stepNames = ['Basic Information', 'Configuration', 'Security Settings', 'Question Selection']
function Toggle({ label, desc, icon, defaultChecked = true }) {
  return <div className="flex items-center justify-between p-md border border-outline-variant rounded-lg hover:bg-surface-container-low transition-colors"><div className="flex items-center"><div className="w-10 h-10 rounded bg-primary-container flex items-center justify-center mr-md"><Icon className="text-white">{icon}</Icon></div><div><p className="text-sm font-bold text-on-surface">{label}</p><p className="text-xs text-on-surface-variant">{desc}</p></div></div><label className="relative inline-flex items-center cursor-pointer"><input type="checkbox" defaultChecked={defaultChecked} className="sr-only peer" /><div className="w-11 h-6 bg-outline-variant rounded-full peer peer-checked:after:translate-x-full after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-secondary-container" /></label></div>
}
export default function CreateExam({ page, setPage }) {
  const [step, setStep] = useState(1)
  const total = 4
  const next = () => step < total ? setStep(step + 1) : alert('Exam Published Successfully!')
  return <TeacherShell page={page} setPage={setPage} title="Create New Examination">
    <div className="w-full bg-surface-container-low h-1 fixed left-64 top-16 z-40"><div className="h-full bg-secondary-container transition-all" style={{ width: `${step / total * 100}%` }} /></div>
    <div className="max-w-[850px] mx-auto pt-lg">
      <div className="mb-lg"><div className="flex justify-between items-center text-xs font-bold text-on-surface-variant mb-base"><span>STEP {step} OF {total}</span><span>{stepNames[step - 1]}</span></div><div className="flex gap-xs">{[1, 2, 3, 4].map(n => <div key={n} className={`h-1 flex-1 rounded-full ${n <= step ? 'bg-secondary-container' : 'bg-surface-container-highest'}`} />)}</div></div>
      <form className="space-y-lg" onSubmit={e => e.preventDefault()}>
        {step === 1 && <div className="card p-lg"><h3 className="text-xl font-bold text-primary mb-lg">Exam Identity</h3><div className="space-y-md"><div><label className="block text-sm font-bold text-on-surface-variant mb-xs">Exam Title</label><input className="input" placeholder="e.g. Mid-Term Calculus Fundamentals" /></div><div className="grid md:grid-cols-2 gap-md"><div><label className="block text-sm font-bold text-on-surface-variant mb-xs">Course / Subject</label><select className="input"><option>Mathematics</option><option>Computer Science</option><option>Physics</option><option>Data Ethics</option></select></div><div><label className="block text-sm font-bold text-on-surface-variant mb-xs">Class / Batch</label><select className="input"><option>Section A - 2026</option><option>Section B - 2026</option><option>Honors Program</option></select></div></div></div></div>}
        {step === 2 && <div className="card p-lg"><h3 className="text-xl font-bold text-primary mb-lg">Scheduling & Grading</h3><div className="grid md:grid-cols-2 gap-md"><div><label className="block text-sm font-bold text-on-surface-variant mb-xs">Date</label><input type="date" className="input" /></div><div><label className="block text-sm font-bold text-on-surface-variant mb-xs">Start Time</label><input type="time" className="input" /></div><div><label className="block text-sm font-bold text-on-surface-variant mb-xs">Duration</label><input type="number" defaultValue="60" className="input" /></div><div><label className="block text-sm font-bold text-on-surface-variant mb-xs">Total Marks</label><input type="number" defaultValue="100" className="input" /></div></div></div>}
        {step === 3 && <div className="card p-lg"><div className="flex items-center justify-between mb-lg"><h3 className="text-xl font-bold text-primary">Security & Proctoring</h3><span className="pill bg-tertiary-fixed text-on-tertiary-container flex items-center gap-xs"><Icon className="text-sm">verified_user</Icon> AI SECURE ENABLED</span></div><div className="space-y-md"><Toggle icon="visibility" label="AI Proctoring" desc="Continuous eye tracking and movement detection" /><Toggle icon="face" label="Face & Voice Verification" desc="Identity check before exam start" /><Toggle icon="lock" label="Lockdown Browser Mode" desc="Prevents switching tabs or opening other apps" /></div></div>}
        {step === 4 && <div><div className="grid md:grid-cols-2 gap-md"><button type="button" className="group p-lg border border-outline-variant rounded-xl bg-surface-container-lowest hover:border-secondary-container transition-all text-left"><div className="w-12 h-12 rounded-full bg-surface-container-high flex items-center justify-center mb-md group-hover:bg-secondary-fixed"><Icon className="text-primary">auto_awesome</Icon></div><h4 className="text-xl font-bold text-primary mb-xs">Select from Question Bank</h4><p className="text-on-surface-variant">Browse verified questions by curriculum topic.</p></button><button type="button" className="group p-lg border border-outline-variant rounded-xl bg-surface-container-lowest hover:border-secondary-container transition-all text-left"><div className="w-12 h-12 rounded-full bg-surface-container-high flex items-center justify-center mb-md group-hover:bg-secondary-fixed"><Icon className="text-primary">edit_note</Icon></div><h4 className="text-xl font-bold text-primary mb-xs">Manual Entry</h4><p className="text-on-surface-variant">Create new questions from scratch.</p></button></div><div className="mt-md bg-surface-container-low border border-dashed border-outline rounded-xl p-xl flex flex-col items-center text-center"><Icon className="text-6xl text-outline-variant mb-md">inventory_2</Icon><p className="text-xl text-on-surface-variant">No questions selected yet</p><p className="text-sm text-outline mb-md">Total Marks: 0 / 100</p></div></div>}
        <div className="flex items-center justify-between pt-md"><button type="button" onClick={() => setStep(Math.max(1, step - 1))} className={`${step === 1 ? 'invisible' : ''} px-lg py-sm border border-outline-variant rounded-lg text-sm font-bold text-on-surface-variant hover:bg-surface-container-high`}>Previous</button><div className="flex gap-md"><button type="button" className="px-lg py-sm text-sm font-bold text-on-surface-variant hover:bg-surface-container-high rounded-lg">Save Draft</button><button type="button" onClick={next} className={`px-xl py-sm ${step === total ? 'btn-secondary' : 'btn-primary'}`}>{step === total ? 'Publish Exam' : 'Next Step'}</button></div></div>
      </form>
    </div>
  </TeacherShell>
}
