import { useState } from 'react'
import TeacherShell, { Icon, StatCard } from '../../../components/TeacherShell.jsx'

export default function ExamScheduling({ page, setPage }) {
  const [view, setView] = useState('Week')
  const events = [['OS Midterm', 'Mon 10:30 AM', 'Section A', 'Published'], ['DBMS Quiz', 'Tue 02:00 PM', 'Section B', 'Draft'], ['CN Unit Test', 'Wed 11:00 AM', 'Honors', 'Published'], ['AOA Practical', 'Fri 09:00 AM', 'Lab Batch', 'Needs Review']]
  return <TeacherShell page={page} setPage={setPage} title="Exam Scheduling">
    <div className="flex justify-between items-end mb-lg"><div><h1 className="text-4xl font-extrabold text-primary">Exam Scheduling</h1><p className="text-on-surface-variant">Plan exam dates, assign batches, and avoid timetable conflicts.</p></div><div className="flex gap-xs bg-surface-container-low p-xs rounded-lg border border-outline-variant">{['Day', 'Week', 'Month'].map(v => <button key={v} onClick={() => setView(v)} className={`px-md py-xs rounded ${view === v ? 'bg-primary text-white' : 'text-on-surface-variant'}`}>{v}</button>)}</div></div>
    <div className="grid md:grid-cols-3 gap-gutter mb-lg"><StatCard label="This Week" value="07" icon="event" /><StatCard label="Conflicts" value="02" icon="warning" /><StatCard label="Rooms Allocated" value="18" icon="meeting_room" /></div>
    <div className="bento-grid"><section className="col-span-8 card p-md"><div className="flex justify-between mb-md"><h2 className="text-xl font-bold text-primary">{view} Schedule</h2><button onClick={() => setPage('createExam')} className="btn-secondary px-md py-sm flex gap-xs"><Icon>add</Icon>New Exam</button></div><div className="grid md:grid-cols-5 gap-sm">{['Mon', 'Tue', 'Wed', 'Thu', 'Fri'].map((d, i) => <div key={d} className="min-h-80 bg-surface-container-low rounded-xl p-sm"><p className="font-bold text-primary mb-sm">{d}</p>{events.filter((_, idx) => idx === i || idx % 5 === i).map(e => <div key={e[0]} className="p-sm mb-sm bg-white border border-outline-variant rounded-lg"><p className="font-bold text-sm text-primary">{e[0]}</p><p className="text-xs text-on-surface-variant">{e[1]}</p><span className="text-[10px] font-bold text-secondary">{e[2]}</span></div>)}</div>)}</div></section><section className="col-span-4 card p-md"><h2 className="text-xl font-bold text-primary mb-md">Upcoming Exams</h2>{events.map(e => <div key={e[0]} className="p-sm mb-sm border border-outline-variant rounded-lg"><div className="flex justify-between"><b className="text-primary">{e[0]}</b><span className="pill bg-surface-container-high text-on-surface-variant">{e[3]}</span></div><p className="text-sm text-on-surface-variant mt-xs">{e[1]} • {e[2]}</p></div>)}</section></div>
  </TeacherShell>
}
