import { useState } from 'react'
import TeacherShell, { Icon, StatCard } from '../../../components/TeacherShell.jsx'

const rows = [['Explain the principles of thermodynamics...', 'In a closed system, entropy can never decrease over time...', 'Subjective', 'Physics', 'Hard', 'Oct 12, 2025'], ['Which element has atomic number 79?', 'A) Gold B) Silver C) Platinum D) Copper', 'MCQ', 'Chemistry', 'Easy', 'Nov 05, 2025'], ['Describe the impact of the Magna Carta...', 'Historical significance of the 1215 charter on modern law...', 'Subjective', 'History', 'Medium', 'Dec 01, 2025'], ['Solve for x: 2x² + 5x - 3 = 0', 'Quadratic equation root finding assessment...', 'MCQ', 'Mathematics', 'Medium', 'Dec 14, 2025']]
export default function QuestionBankManagement({ page, setPage }) {
  const [open, setOpen] = useState(false)
  const [selected, setSelected] = useState([])
  return <TeacherShell page={page} setPage={setPage} title="Question Bank" search>
    <div className="flex justify-between items-end mb-lg"><div><h1 className="text-4xl font-extrabold text-primary">Question Bank</h1><p className="text-on-surface-variant">Manage your institution's central assessment repository.</p></div><div className="relative"><button onClick={() => setOpen(!open)} className="btn-primary px-md py-sm flex items-center gap-xs"><Icon>add_circle</Icon>Add New Question<Icon>expand_more</Icon></button>{open && <div className="absolute top-full right-0 mt-xs w-48 bg-surface-container-lowest border border-outline-variant rounded-lg shadow-xl py-xs z-50">{['Manual Entry', 'Bulk CSV Import', 'AI Generation'].map((x, i) => <button key={x} className="w-full flex items-center gap-xs px-md py-sm text-sm hover:bg-surface-container-low"><Icon className="text-sm">{['edit_note', 'upload_file', 'smart_toy'][i]}</Icon>{x}</button>)}</div>}</div></div>
    <div className="flex gap-gutter items-start"><aside className="w-72 flex-shrink-0 sticky top-[88px] bg-surface-container-low rounded-xl border border-outline-variant p-md"><div className="flex justify-between mb-md"><h3 className="text-xl font-bold text-primary">Filters</h3><button className="text-xs text-secondary font-bold">RESET</button></div><div className="space-y-md"><div><label className="text-xs font-bold text-on-surface-variant block mb-xs">Subject</label><select className="input"><option>All Subjects</option><option>Advanced Mathematics</option><option>Quantum Physics</option></select></div><div><label className="text-xs font-bold text-on-surface-variant block mb-xs">Difficulty</label>{['Easy', 'Medium', 'Hard'].map((x, i) => <label key={x} className="flex items-center gap-sm p-2 hover:bg-surface-container-high rounded-lg"><input type="checkbox" defaultChecked={i === 1} className="rounded text-secondary" /><span className="text-sm">{x}</span></label>)}</div><div><label className="text-xs font-bold text-on-surface-variant block mb-xs">Question Type</label><div className="flex flex-wrap gap-xs">{['MCQ', 'Subjective', 'True/False', 'Matching'].map(x => <button key={x} className="px-sm py-1 rounded-full border border-outline-variant bg-white text-xs hover:border-secondary">{x}</button>)}</div></div><input type="date" className="input" /></div></aside>
      <div className="flex-1 card overflow-hidden"><table className="w-full text-left table-fixed"><thead><tr className="bg-surface-container-low border-b border-outline-variant"><th className="table-th w-10"><input type="checkbox" /></th><th className="table-th">Question Preview</th><th className="table-th w-[11%]">Type</th><th className="table-th w-[11%]">Subject</th><th className="table-th w-[11%]">Difficulty</th><th className="table-th w-[15%]">Last Used</th><th className="table-th w-[20%] last:text-right">Actions</th></tr></thead><tbody className="divide-y divide-outline-variant">{rows.map((r, i) => <tr key={r[0]} onClick={() => setSelected(s => s.includes(i) ? s.filter(x => x !== i) : [...s, i])} className="hover:bg-surface-container-low cursor-pointer group"><td className="table-td"><input checked={selected.includes(i)} readOnly type="checkbox" /></td><td className="table-td truncate"><div className="flex gap-sm"><div className={`w-2 h-10 rounded-full shrink-0 ${i % 2 ? 'bg-secondary-container' : 'bg-primary'}`} /><div className="min-w-0"><p className="text-sm font-bold text-primary truncate">{r[0]}</p><p className="text-xs text-on-surface-variant truncate">{r[1]}</p></div></div></td><td className="table-td whitespace-nowrap"><span className="pill bg-surface-container-highest text-on-surface-variant">{r[2]}</span></td><td className="table-td whitespace-nowrap text-sm">{r[3]}</td><td className="table-td whitespace-nowrap"><span className={`text-xs font-bold ${r[4] === 'Hard' ? 'text-error' : r[4] === 'Easy' ? 'text-on-tertiary-container' : 'text-secondary'}`}>● {r[4]}</span></td><td className="table-td whitespace-nowrap text-xs text-on-surface-variant">{r[5]}</td><td className="table-td whitespace-nowrap"><div className="flex justify-end gap-xs opacity-0 group-hover:opacity-100">{['edit', 'content_copy', 'delete'].map(ic => <button key={ic} className="p-2 hover:bg-surface-container-high rounded-full"><Icon className="text-sm">{ic}</Icon></button>)}</div></td></tr>)}</tbody></table><div className="bg-surface-container-low px-md py-sm flex justify-between border-t border-outline-variant"><span className="text-xs text-on-surface-variant">Showing 1 to 4 of 248 questions</span><div className="flex gap-xs"><button className="px-3 py-1 bg-primary text-white rounded text-xs">1</button><button className="px-3 py-1 bg-surface-container-high rounded text-xs">2</button><button className="px-3 py-1 bg-surface-container-high rounded text-xs">3</button><span className="text-xs text-on-surface-variant">...</span></div></div></div></div>
    <div className="grid md:grid-cols-4 gap-gutter mt-lg"><StatCard label="Total Repository" value="12,482" hint="+12% this term" /><StatCard label="AI Generated" value="3,120" icon="auto_awesome" /><StatCard label="Unused" value="845" icon="archive" /><StatCard label="Average Difficulty" value="Medium" /></div>
  </TeacherShell>
}
