import { useState } from 'react'
import TeacherShell, { Icon } from '../../../components/TeacherShell.jsx'

export default function SyllabusMapping({ page, setPage }) {
  const topics = ['Process Scheduling', 'Deadlock', 'Memory Management', 'File Systems', 'Disk Scheduling']
  const [selected, setSelected] = useState(['Deadlock', 'Memory Management'])
  return <TeacherShell page={page} setPage={setPage} title="Syllabus Mapping">
    <div className="mb-lg"><h1 className="text-4xl font-extrabold text-primary">Syllabus Mapping</h1><p className="text-on-surface-variant">Map questions and exams to curriculum outcomes and topic coverage.</p></div>
    <div className="bento-grid"><section className="col-span-4 card p-md"><h2 className="text-xl font-bold text-primary mb-md">Curriculum Tree</h2>{topics.map(t => <button key={t} onClick={() => setSelected(s => s.includes(t) ? s.filter(x => x !== t) : [...s, t])} className={`w-full p-sm mb-sm rounded-lg text-left border ${selected.includes(t) ? 'border-secondary-container bg-secondary-container/10' : 'border-outline-variant hover:bg-surface-container-low'}`}><div className="flex justify-between"><b>{t}</b>{selected.includes(t) && <Icon className="text-secondary">check_circle</Icon>}</div><p className="text-xs text-on-surface-variant">CO-{topics.indexOf(t) + 1} • {12 + topics.indexOf(t) * 3} questions</p></button>)}</section><section className="col-span-8 card p-md"><h2 className="text-xl font-bold text-primary mb-md">Coverage Matrix</h2><div className="overflow-x-auto"><table className="w-full"><thead><tr className="bg-surface-container-low"><th className="table-th">Topic</th><th className="table-th">Questions</th><th className="table-th">Marks</th><th className="table-th">Coverage</th></tr></thead><tbody>{topics.map((t, i) => <tr key={t} className="border-t border-outline-variant"><td className="table-td font-bold text-primary">{t}</td><td className="table-td">{12 + i * 3}</td><td className="table-td">{10 + i * 5}</td><td className="table-td"><div className="h-2 bg-surface-container-high rounded-full"><div className="h-full bg-secondary-container rounded-full" style={{ width: (55 + i * 8) + '%' }} /></div></td></tr>)}</tbody></table></div></section><section className="col-span-12 card p-md"><h2 className="text-xl font-bold text-primary mb-md">AI Recommendation</h2><p className="text-on-surface-variant">Memory Management and Disk Scheduling have lower coverage compared to previous exams. Add 4–6 medium-level questions to balance the paper.</p></section></div>
  </TeacherShell>
}
