import { useState } from 'react'
import TeacherShell, { Icon, StatCard } from '../../../components/TeacherShell.jsx'

export default function LiveExamControlRoom({ page, setPage }) {
  const [lockdown, setLockdown] = useState(true)
  return <TeacherShell page={page} setPage={setPage} title="Live Exam Control Room">
    <div className="mb-lg flex justify-between items-end"><div><span className="pill bg-tertiary-fixed text-on-tertiary-container">CONTROL ROOM ACTIVE</span><h1 className="text-4xl font-extrabold text-primary mt-sm">Operating Systems Midterm</h1><p className="text-on-surface-variant">Session ID: ED-9921-X • 142 students • Offline secure mode</p></div><button onClick={() => setLockdown(!lockdown)} className={`${lockdown ? 'btn-secondary' : 'btn-primary'} px-lg py-sm flex gap-xs`}><Icon>{lockdown ? 'lock' : 'lock_open'}</Icon>{lockdown ? 'Lockdown ON' : 'Lockdown OFF'}</button></div>
    <div className="grid md:grid-cols-5 gap-gutter mb-lg"><StatCard label="Students" value="142" /><StatCard label="Submitted" value="18" /><StatCard label="Flagged" value="05" /><StatCard label="Avg Progress" value="42%" /><StatCard label="Time Left" value="01:12" /></div>
    <div className="bento-grid"><section className="col-span-8 card p-md"><div className="flex justify-between mb-md"><h2 className="text-xl font-bold text-primary">Live Proctoring Grid</h2><button onClick={() => setPage('monitoring')} className="text-secondary font-bold">Open detailed monitoring</button></div><div className="grid md:grid-cols-4 gap-sm">{Array.from({ length: 12 }).map((_, i) => <div key={i} className="aspect-video rounded-lg bg-primary-container relative overflow-hidden"><div className="absolute inset-0 bg-gradient-to-br from-primary-container to-primary" /><div className="relative z-10 h-full p-xs flex flex-col justify-between text-white"><div className="flex justify-between"><span className={`text-[10px] px-1 rounded ${[2, 7, 10].includes(i) ? 'bg-error' : 'bg-tertiary-fixed text-on-tertiary-container'}`}>{[2, 7, 10].includes(i) ? 'RISK' : 'OK'}</span><Icon className="text-sm">videocam</Icon></div><span className="text-xs font-bold">Student {i + 1}</span></div></div>)}</div></section><section className="col-span-4 card p-md"><h2 className="text-xl font-bold text-primary mb-md">Control Actions</h2>{[['Broadcast Message', 'campaign'], ['Pause Exam', 'pause_circle'], ['Force Submit', 'upload'], ['Download Logs', 'download']].map(([x, ic], i) => <button key={x} className={`w-full p-sm mb-sm rounded-lg flex justify-between ${i === 2 ? 'bg-error-container text-error' : 'border border-outline-variant hover:bg-surface-container-low'}`}>{x}<Icon>{ic}</Icon></button>)}<div className="mt-md p-md bg-primary-container text-white rounded-xl"><p className="text-xs uppercase opacity-70">AI Room Status</p><h3 className="text-2xl font-bold">Stable</h3><p className="text-sm text-primary-fixed-dim">No mass anomaly detected.</p></div></section><section className="col-span-12 card p-md"><h2 className="text-xl font-bold text-primary mb-md">Live Activity Feed</h2>{['Student 18 submitted answer 12', 'AI flagged possible face mismatch for Student 07', 'Broadcast message delivered to all candidates', 'Student 42 reconnected after network drop'].map((x, i) => <div key={i} className="flex items-center gap-md p-sm border-b border-outline-variant last:border-0"><div className={`w-8 h-8 rounded-full grid place-items-center text-sm ${i === 1 ? 'bg-error-container text-error' : 'bg-surface-container-highest text-on-surface-variant'}`}><Icon>{['check_circle', 'error_outline', 'campaign', 'wifi'][i]}</Icon></div><p className="text-sm">{x}</p></div>)}</section></div>
  </TeacherShell>
}
