import { useState } from 'react'
import TeacherShell, { Icon, StatCard } from '../../../components/TeacherShell.jsx'

const students = ['Arjun Sharma', 'Riya Mehta', 'Kabir Khan', 'Sneha Iyer', 'Om Patel', 'Nisha Rao', 'Aman Verma', 'Tara Shah']
export default function StudentMonitoring({ page, setPage }) {
  const [active, setActive] = useState(students[0])
  return <TeacherShell page={page} setPage={setPage} title="Student Monitoring">
    <div className="mb-lg"><span className="pill bg-tertiary-fixed text-on-tertiary-container">LIVE EXAM ACTIVE</span><h1 className="text-4xl font-extrabold text-primary mt-sm">Student Monitoring</h1><p className="text-on-surface-variant">Watch candidate feeds, identity confidence, system health, and risk flags.</p></div>
    <div className="grid md:grid-cols-4 gap-gutter mb-lg"><StatCard label="Online" value="142" /><StatCard label="High Risk" value="05" /><StatCard label="Face Verified" value="137" /><StatCard label="Avg Network" value="31ms" /></div>
    <div className="grid lg:grid-cols-[1fr_360px] gap-gutter"><section className="card p-md"><div className="grid md:grid-cols-3 gap-sm">{students.map((s, i) => <button key={s} onClick={() => setActive(s)} className={`relative aspect-video rounded-xl overflow-hidden border-2 ${active === s ? 'border-secondary-container' : 'border-outline-variant'} bg-primary text-white text-left p-sm`}><div className="absolute inset-0 bg-gradient-to-br from-primary-container to-primary" /><div className="relative z-10 h-full flex flex-col justify-between"><div className="flex justify-between"><span className={`pill ${i === 2 || i === 5 ? 'bg-error text-white' : 'bg-tertiary-fixed text-on-tertiary-container'}`}>{i === 2 || i === 5 ? 'Risk' : 'Stable'}</span><Icon className="text-white/70">videocam</Icon></div><div><p className="font-bold">{s}</p><p className="text-xs text-white/70">ID: ED-20{40 + i}</p></div></div></button>)}</div></section><aside className="card p-md"><h2 className="text-xl font-bold text-primary mb-md">Candidate Detail</h2><div className="w-full aspect-video bg-primary-container rounded-xl grid place-items-center text-white mb-md"><div className="text-center"><div className="w-20 h-20 bg-secondary-container text-primary rounded-full grid place-items-center text-2xl font-bold mx-auto mb-sm">{active.split(' ').map(x => x[0]).join('')}</div><b>{active}</b></div></div>{[['Face Match', '96%'], ['Audio Noise', 'Low'], ['Tab Switches', '0'], ['Object Detection', 'Clear']].map(([a, b]) => <div key={a} className="flex justify-between p-sm border-b border-outline-variant"><span className="text-on-surface-variant">{a}</span><b className="text-primary">{b}</b></div>)}<button onClick={() => setPage('alerts')} className="w-full mt-md btn-secondary py-sm">Open Risk Alerts</button></aside></div>
  </TeacherShell>
}
