import { useState } from 'react'
import TeacherShell, { Icon, StatCard } from '../../../components/TeacherShell.jsx'

const alerts = []
export default function SuspiciousActivityAlerts({ page, setPage }) {
  const [filter, setFilter] = useState('All')
  const shown = filter === 'All' ? alerts : alerts.filter(a => a[0] === filter)
  return <TeacherShell page={page} setPage={setPage} title="Suspicious Activity Alerts">
    <div className="flex justify-between items-end mb-lg"><div><h1 className="text-4xl font-extrabold text-primary">Suspicious Activity Alerts</h1><p className="text-on-surface-variant">Review AI-generated integrity incidents from live and completed exams.</p></div><div className="flex gap-xs bg-surface-container-low p-xs rounded-lg border border-outline-variant">{['All', 'High', 'Medium', 'Low'].map(f => <button key={f} onClick={() => setFilter(f)} className={`px-md py-xs rounded text-sm ${filter === f ? 'bg-primary text-white' : 'text-on-surface-variant'}`}>{f}</button>)}</div></div>
    <div className="grid md:grid-cols-4 gap-gutter mb-lg"><StatCard label="Total Alerts" value="—" /><StatCard label="High Priority" value="—" /><StatCard label="Resolved" value="—" /><StatCard label="Pending" value="—" /></div>
    <div className="grid lg:grid-cols-[1fr_360px] gap-gutter"><section className="card overflow-hidden"><div className="divide-y divide-outline-variant">{shown.length === 0 ? <p className="p-md text-center text-on-surface-variant">No alerts to display.</p> : shown.map((a, i) => <div key={i} className="p-md hover:bg-surface-container-low flex items-center justify-between"><div className="flex gap-md"><div className={`w-12 h-12 rounded-lg grid place-items-center ${a[0] === 'High' ? 'bg-error-container text-error' : a[0] === 'Medium' ? 'bg-secondary-fixed text-secondary' : 'bg-surface-container-high text-on-surface-variant'}`}><Icon>{a[4]}</Icon></div><div><h3 className="font-bold text-primary">{a[1]}</h3><p className="text-sm text-on-surface-variant">{a[2]} • {a[3]}</p></div></div><div className="flex gap-xs"><span className={`pill ${a[0] === 'High' ? 'bg-error text-white' : a[0] === 'Medium' ? 'bg-secondary-container text-primary' : 'bg-surface-container-high text-on-surface-variant'}`}>{a[0]}</span><button className="px-sm py-xs border border-outline-variant rounded-lg text-sm">Review</button></div></div>)}</div></section><aside className="card p-md"><h2 className="text-xl font-bold text-primary mb-md">Incident Policy</h2><p className="text-on-surface-variant text-sm">Alert policy guidelines will appear here.</p></aside></div>
  </TeacherShell>
}
