import TeacherShell, { Icon, StatCard } from '../../../components/TeacherShell.jsx'

export default function TeacherDashboard({ page, setPage }) {
  const exams = [
    ['Operating Systems Midterm', 'Live now', '142 students', 'monitoring', 'liveRoom'],
    ['Data Structures Quiz', 'Scheduled 2:00 PM', 'Section B', 'event', 'scheduling'],
    ['AI Ethics Assignment', 'Evaluation pending', '45 scripts', 'grading', 'answerEvaluation'],
  ]
  return <TeacherShell page={page} setPage={setPage} title="Teacher Dashboard">
    <section className="mb-lg"><span className="pill bg-secondary-fixed text-secondary">Academic Control Room</span><h1 className="text-4xl font-extrabold text-primary mt-sm">Good morning, Professor</h1><p className="text-on-surface-variant">Monitor exams, review suspicious activity, and manage assessments from one dashboard.</p></section>
    <div className="grid md:grid-cols-4 gap-gutter mb-lg"><StatCard label="Active Exams" value="03" hint="1 requires attention" icon="assignment"/><StatCard label="Students Online" value="428" hint="Across 6 batches" icon="groups"/><StatCard label="Answers Pending" value="128" hint="AI pre-graded" icon="fact_check"/><StatCard label="Risk Alerts" value="17" hint="5 high priority" icon="warning"/></div>
    <div className="bento-grid">
      <section className="col-span-8 card overflow-hidden"><div className="p-md border-b border-outline-variant flex justify-between"><h2 className="text-xl font-bold text-primary">Today's Assessment Queue</h2><button onClick={()=>setPage('createExam')} className="btn-secondary px-md py-sm">Create Exam</button></div><div className="divide-y divide-outline-variant">{exams.map(([name,status,meta,icon,target])=><button key={name} onClick={()=>setPage(target)} className="w-full p-md flex items-center justify-between hover:bg-surface-container-low text-left"><div className="flex items-center gap-md"><div className="w-12 h-12 rounded-lg bg-primary-fixed grid place-items-center text-primary"><Icon>{icon}</Icon></div><div><h3 className="font-bold text-primary">{name}</h3><p className="text-sm text-on-surface-variant">{meta}</p></div></div><span className="pill bg-surface-container-high text-on-surface-variant">{status}</span></button>)}</div></section>
      <section className="col-span-4 p-md bg-primary-container text-white rounded-xl border border-outline-variant shadow-lg"><h2 className="text-xl font-bold mb-md">AI Integrity Summary</h2>{['Face mismatch patterns', 'Tab switch attempts', 'Noise anomaly clusters'].map((x,i)=><div key={x} className="mb-md"><div className="flex justify-between text-sm mb-xs"><span>{x}</span><b>{[12,7,21][i]}</b></div><div className="h-2 bg-white/10 rounded-full overflow-hidden"><div className="h-full bg-secondary-container" style={{width:[45,25,70][i]+'%'}}/></div></div>)}<button onClick={()=>setPage('alerts')} className="mt-md w-full py-sm bg-white/10 rounded-lg hover:bg-white/20">Open Alerts</button></section>
      <section className="col-span-12 card p-md"><h2 className="text-xl font-bold text-primary mb-md">Quick Actions</h2><div className="grid md:grid-cols-5 gap-sm">{[['Create Exam','add','createExam'],['Schedule','event','scheduling'],['Question Bank','database','questionBank'],['Reports','analytics','reports'],['Live Room','videocam','liveRoom']].map(([label,icon,target])=><button key={label} onClick={()=>setPage(target)} className="p-md border border-outline-variant rounded-xl hover:border-secondary-container hover:bg-secondary-container/10 text-left"><Icon className="text-primary">{icon}</Icon><p className="font-bold mt-sm">{label}</p></button>)}</div></section>
    </div>
  </TeacherShell>
}
