import { useState } from 'react'
import { Icon } from '../../../components/TeacherShell.jsx'

export default function TeacherLogin({ onLogin }) {
  const [show, setShow] = useState(false)
  return <div className="min-h-screen bg-background flex flex-col">
    <header className="h-16 px-gutter flex items-center border-b border-outline-variant bg-surface"><div className="flex items-center gap-xs"><Icon className="text-primary text-3xl">shield</Icon><h1 className="text-2xl font-extrabold text-primary">Skillo</h1><span className="ml-sm pill bg-secondary-fixed text-secondary">Teacher Portal</span></div></header>
    <main className="flex-1 grid md:grid-cols-2">
      <section className="hidden md:flex bg-primary text-white p-xl relative overflow-hidden items-center"><div className="absolute -top-32 -left-32 w-96 h-96 bg-secondary-container/30 rounded-full blur-3xl"/><div className="absolute -bottom-32 -right-32 w-96 h-96 bg-primary-fixed-dim/20 rounded-full blur-3xl"/><div className="relative max-w-xl"><span className="pill bg-secondary-container text-on-secondary-container">Encrypted Faculty Access</span><h2 className="text-5xl font-extrabold mt-md leading-tight">Command center for secure assessments.</h2><p className="text-primary-fixed-dim text-lg mt-md leading-relaxed">Create exams, monitor active sessions, evaluate answers with AI support, and protect academic integrity in one unified portal.</p><div className="mt-lg grid grid-cols-3 gap-sm"><div className="p-md rounded-xl bg-white/10"><b>98%</b><p className="text-xs opacity-70">Auto flagged accuracy</p></div><div className="p-md rounded-xl bg-white/10"><b>24/7</b><p className="text-xs opacity-70">Monitoring logs</p></div><div className="p-md rounded-xl bg-white/10"><b>AI</b><p className="text-xs opacity-70">Rubric evaluation</p></div></div></div></section>
      <section className="flex items-center justify-center p-gutter"><form onSubmit={(e)=>{e.preventDefault();onLogin?.()}} className="w-full max-w-md card p-lg"><h2 className="text-3xl font-bold text-primary">Welcome Back</h2><p className="text-on-surface-variant mt-xs mb-lg">Sign in to your secure teacher workspace.</p><label className="text-sm font-bold text-on-surface-variant">Faculty ID / Email</label><div className="relative mt-xs mb-md"><Icon className="absolute left-4 top-1/2 -translate-y-1/2 text-on-surface-variant">person</Icon><input className="input pl-12" placeholder="e.g. prof.sen@institution.edu" /></div><label className="text-sm font-bold text-on-surface-variant">Secure Password</label><div className="relative mt-xs mb-md"><Icon className="absolute left-4 top-1/2 -translate-y-1/2 text-on-surface-variant">lock</Icon><input type={show?'text':'password'} className="input pl-12 pr-12" placeholder="••••••••" /><button type="button" onClick={()=>setShow(!show)} className="absolute right-4 top-1/2 -translate-y-1/2"><Icon>{show?'visibility_off':'visibility'}</Icon></button></div><div className="flex items-center justify-between text-sm mb-lg"><label className="flex items-center gap-xs"><input type="checkbox" className="rounded text-secondary"/> Remember me</label><a href="#" className="font-bold text-secondary hover:underline">Forgot access?</a></div><button className="w-full h-12 btn-primary flex items-center justify-center gap-xs">Sign In <Icon>arrow_forward</Icon></button><div className="mt-lg p-md bg-secondary-container/10 border border-secondary-container/20 rounded-lg flex gap-sm"><Icon className="text-secondary">info</Icon><p className="text-xs text-on-secondary-container">Multi-factor verification may be requested before opening live monitoring rooms.</p></div></form></section>
    </main>
  </div>
}
