import { useState } from 'react'
import TeacherShell, { Icon, StatCard } from '../../../components/TeacherShell.jsx'

export default function StudentIntelligenceProfileViewer({ page, setPage }) {
  const [student, setStudent] = useState('Arjun Sharma')
  const skills = [['Logical Reasoning', 92], ['Quantitative Aptitude', 78], ['Verbal Ability', 85], ['Focus Stability', 88], ['Concept Recall', 74]]
  return <TeacherShell page={page} setPage={setPage} title="Student Intelligence Profile" search>
    <div className="flex justify-between items-end mb-lg"><div><h1 className="text-4xl font-extrabold text-primary">Intelligence Profile Viewer</h1><p className="text-on-surface-variant">Understand student strengths, weaknesses, behavior patterns, and learning gaps.</p></div><select value={student} onChange={e => setStudent(e.target.value)} className="input max-w-[14rem]"><option>Arjun Sharma</option><option>Riya Mehta</option><option>Kabir Khan</option></select></div>
    <div className="grid md:grid-cols-4 gap-gutter mb-lg"><StatCard label="Overall Score" value="88%" /><StatCard label="Consistency" value="High" /><StatCard label="Risk Level" value="Low" /><StatCard label="Growth" value="+12%" /></div>
    <div className="bento-grid"><section className="col-span-5 card p-lg bg-primary-container text-white"><div className="flex items-center gap-md mb-lg"><div className="w-20 h-20 rounded-full bg-secondary-container grid place-items-center text-primary text-2xl font-bold">AS</div><div><h2 className="text-2xl font-bold">{student}</h2><p className="text-primary-fixed-dim">Computer Science • Section A</p></div></div>{skills.map(([s, v]) => <div className="mb-md" key={s}><div className="flex justify-between text-sm mb-xs"><span>{s}</span><b>{v}%</b></div><div className="h-2 bg-white/10 rounded"><div className="h-full bg-secondary-container rounded" style={{ width: v + '%' }} /></div></div>)}</section><section className="col-span-7 card p-md"><h2 className="text-xl font-bold text-primary mb-md">AI Learning Insights</h2>{['Strong analytical reasoning and pattern recognition.', 'Needs practice with time-bound quantitative problems.', 'Best performance window appears between 10 AM and 12 PM.', 'Revision recommended for OS deadlock and paging concepts.'].map((x, i) => <div key={x} className="p-md mb-sm bg-surface-container-low rounded-lg flex gap-sm"><Icon className="text-secondary">{['psychology', 'speed', 'schedule', 'school'][i]}</Icon><p>{x}</p></div>)}</section><section className="col-span-12 card p-md"><h2 className="text-xl font-bold text-primary mb-md">Recent Exam Timeline</h2><div className="grid md:grid-cols-4 gap-sm">{['OS Midterm 88%', 'DBMS Quiz 91%', 'CN Test 76%', 'Python Lab 94%'].map(x => <div key={x} className="p-md border border-outline-variant rounded-xl"><b className="text-primary">{x}</b><p className="text-xs text-on-surface-variant mt-xs">AI feedback generated</p></div>)}</div></section></div>
  </TeacherShell>
}
